CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE assets
  ADD COLUMN IF NOT EXISTS location GEOGRAPHY(POINT, 4326);

ALTER TABLE incidents
  ADD COLUMN IF NOT EXISTS location GEOGRAPHY(POINT, 4326);

ALTER TABLE weather_events
  ADD COLUMN IF NOT EXISTS location GEOGRAPHY(POINT, 4326);
